### PR TITLE
Playwright: Add search page tests

### PR DESCRIPTION
**Pull request by AR-RIFAT**

### CODE REVIEW

**Comment by utas-raymondng** [comment]
@AR-RIFAT file have conflct

**Comment by AR-RIFAT** [comment]
I'll resolve the conflicts. Also, I need to make some changes. I'll let you know when it's ready for review. Thank you

**Comment by utas-raymondng** [comment]
@AR-RIFAT is ready for review?

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Pull request merged**
