### PR TITLE
:sparkles: change default layer to cluster layer

### PR DESCRIPTION
**Pull request by NekoLyn**
in search result page, change the default map layer to cluster layer

### CODE REVIEW

**Comment by utas-raymondng** [comment]
@NekoLyn build failed

**Comment by NekoLyn** [comment]
> @NekoLyn build failed

Thanks! This is due to the failure of playwright test. since the test of map is based on heatmap but this pr changed the default map to cluster. I am attempting to fix that.

**Comment by utas-raymondng** [comment]
ping it over to Ash, you do other more visual appealing task :)

**Comment by NekoLyn** [comment]
> ping it over to Ash, you do other more visual appealing task :)

Thanks! I add this issue in the ticket for Ashraful https://github.com/aodn/aodn-portal-v2/issues/201

**Review by utas-raymondng — APPROVED** [review]
LGTM

**Pull request merged**
