### PR TITLE
Features/5752 paging

### PR DESCRIPTION
**Pull request by utas-raymondng**
1. Fix bug on result list size beyond the bottom
2. Add load more button to fetch next batch, default to 11
3. Change the layout of button "Sort" and "View" and try match with design
4. The showing total and number of record works but looks bad, @NekoLyn can you after approve the change, fix it in your ticket?

### CODE REVIEW

**Comment by NekoLyn** [comment]
No problem

**Review by NekoLyn — APPROVED** [review]
LGTM

**Comment by NekoLyn** [comment]
image
If there is not result it might a placeholder like 'no result found'. I will comfirm with @quye04  and fix this issue in [#5746](https://github.com/aodn/backlog/issues/5746)

**Comment by utas-raymondng** [comment]
yes thanks I think it is part of the error handling

**Pull request merged**
